# Copyright (c) 2018 Sergey Burnevsky (sergey.burnevsky @ gmail.com)
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

script:
  - ./travis.sh

env:
  global:
    CODECOV_TOKEN="2de04452-c6a6-403b-aeb1-423911776c76"

after_success:
  - bash <(curl -s https://codecov.io/bash)
